import { useEffect, useState } from 'react'

interface GenerateRequest {
  bpm: number
  key: string
  provider: string
  model: string
  noLlm: boolean
  bars: number
  groove: string
  offlineStyle: string
}

interface GenerateResult {
  files: string[]
  elapsed: string
  seed: string
}

// Generated by Wails during `wails dev` or `wails build`.
// @ts-ignore
import { Generate, OpenOutputFolder } from '../../wailsjs/go/main/AppService'
// @ts-ignore
import { EventsOn } from '../../wailsjs/runtime/runtime'

const KEYS = [
  'Am', 'Bm', 'Cm', 'Dm', 'Em', 'Fm', 'Gm',
  'C', 'D', 'E', 'F', 'G', 'A', 'B',
  'F#m', 'C#m', 'Bbm',
  'Am-dorian', 'Bm-dorian', 'Em-dorian',
  'Em-phrygian', 'Bm-phrygian',
  'G-mixolydian', 'A-mixolydian', 'D-mixolydian',
  'C-lydian', 'D-lydian',
]
const GROOVES = ['straight', 'mpc60', 'linndrum', 'humanize']
const STYLES = ['melodic', 'hypnotic', 'driving', 'minimal']
const PROVIDERS = ['claude', 'ollama', 'openai', 'gemini', 'offline']
const BARS_OPTS = [16, 32, 64, 128]

function bpmGenre(bpm: number): string {
  if (bpm < 100) return 'Downtempo / Ambient'
  if (bpm < 115) return 'Deep house / Nu-disco'
  if (bpm < 122) return 'Tech house / Organic'
  if (bpm < 130) return 'Progressive / Melodic techno'
  if (bpm < 138) return 'Peak-time techno'
  return 'Hard techno / Industrial'
}

export interface Params {
  bpm: number
  key: string
  bars: number
  groove: string
  style: string
  provider: string
  drums: boolean
}

interface GenerationConsoleProps {
  params: Params
  setParams: (p: Params) => void
}

export function GenerationConsole({ params, setParams }: GenerationConsoleProps) {
  const { bpm, key, bars, groove, style, provider } = params
  const [log, setLog] = useState<string[]>([])
  const [files, setFiles] = useState<string[]>([])
  const [running, setRunning] = useState(false)

  useEffect(() => {
    const off = EventsOn('progress', (msg: string) => {
      setLog(prev => [...prev, msg])
    })
    return () => {
      if (typeof off === 'function') off()
    }
  }, [])

  const handleGenerate = async () => {
    setRunning(true)
    setLog([])
    setFiles([])
    try {
      const req: GenerateRequest = {
        bpm,
        key,
        provider,
        model: '',
        noLlm: provider === 'offline',
        bars,
        groove,
        offlineStyle: style,
      }
      const result: GenerateResult = await Generate(req)
      setFiles(result.files)
      setLog(prev => [...prev, `Done in ${result.elapsed}`, `Seed ${result.seed}`])
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : String(err)
      setLog(prev => [...prev, `Error: ${msg}`])
    } finally {
      setRunning(false)
    }
  }

  return (
    <div className="row" style={{ gridTemplateColumns: '1.1fr 1.4fr' }}>
      <div className="cell">
        <div className="eyebrow" style={{ marginBottom: 22 }}>Parameters</div>

        <div style={{ marginBottom: 22 }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'baseline', marginBottom: 8 }}>
            <span className="label">BPM</span>
            <span className="mono" style={{ fontSize: 13, color: 'var(--fg-dim)' }}>{bpmGenre(bpm)}</span>
          </div>
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 70px', gap: 14, alignItems: 'center' }}>
            <input type="range" min="80" max="150" step="1" value={bpm} onChange={e => setParams({ ...params, bpm: parseInt(e.target.value, 10) })} />
            <div className="mono" style={{ fontSize: 28, fontWeight: 500, textAlign: 'right', letterSpacing: '-0.02em' }}>{bpm}</div>
          </div>
        </div>

        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 18, marginBottom: 22 }}>
          <div>
            <div className="label" style={{ marginBottom: 8 }}>Key and mode</div>
            <select value={key} onChange={e => setParams({ ...params, key: e.target.value })}>
              {KEYS.map(k => <option key={k} value={k}>{k}</option>)}
            </select>
          </div>
          <div>
            <div className="label" style={{ marginBottom: 8 }}>Bars</div>
            <select value={bars} onChange={e => setParams({ ...params, bars: parseInt(e.target.value, 10) })}>
              {BARS_OPTS.map(b => <option key={b} value={b}>{b}</option>)}
            </select>
          </div>
        </div>

        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 18, marginBottom: 22 }}>
          <div>
            <div className="label" style={{ marginBottom: 8 }}>Groove</div>
            <select value={groove} onChange={e => setParams({ ...params, groove: e.target.value })}>
              {GROOVES.map(g => <option key={g} value={g}>{g}</option>)}
            </select>
          </div>
          <div>
            <div className="label" style={{ marginBottom: 8 }}>Offline style</div>
            <select value={style} onChange={e => setParams({ ...params, style: e.target.value })}>
              {STYLES.map(s => <option key={s} value={s}>{s}</option>)}
            </select>
          </div>
        </div>

        <div style={{ marginBottom: 22 }}>
          <div className="label" style={{ marginBottom: 8 }}>Provider</div>
          <div style={{ display: 'flex', gap: 1, background: 'var(--line)', border: '1px solid var(--line)' }}>
            {PROVIDERS.map(p => (
              <button
                key={p}
                type="button"
                onClick={() => setParams({ ...params, provider: p })}
                className="mono"
                style={{
                  flex: 1,
                  padding: '10px 8px',
                  background: provider === p ? 'var(--fg)' : 'var(--bg)',
                  color: provider === p ? 'var(--bg)' : 'var(--fg-dim)',
                  border: 0,
                  cursor: 'pointer',
                  fontSize: 11,
                  letterSpacing: '0.12em',
                  textTransform: 'uppercase',
                }}
              >
                {p}
              </button>
            ))}
          </div>
        </div>

        <button className="btn primary" style={{ width: '100%', fontSize: 13, padding: '14px 0' }} onClick={handleGenerate} disabled={running}>
          {running ? 'Generating...' : 'Generate'}
        </button>
      </div>

      <div className="cell" style={{ background: 'var(--bg-1)', display: 'flex', flexDirection: 'column', gap: 14 }}>
        <div className="eyebrow">Generation log</div>
        <pre className="code" style={{ background: 'var(--bg)', flex: 1, margin: 0, minHeight: 120 }}>
          {log.length === 0 ? '# Press Generate to start...' : log.join('\n')}
        </pre>

        {files.length > 0 && (
          <div style={{ borderTop: '1px solid var(--line)', paddingTop: 14 }}>
            <div className="eyebrow" style={{ marginBottom: 10 }}>Output files</div>
            {files.map(f => (
              <div key={f} className="mono" style={{ fontSize: 12, color: 'var(--fg-dim)', marginBottom: 6 }}>
                {f}
              </div>
            ))}
            <button className="btn ghost" style={{ marginTop: 12, width: '100%' }} onClick={() => OpenOutputFolder()}>
              Open Folder
            </button>
          </div>
        )}
      </div>
    </div>
  )
}
